

services:
  # 1. LE BACKEND (LARAVEL)
  app:
    build:
      context: ./backend # Vérifie que ton dossier Laravel s'appelle bien 'backend'
      dockerfile: Dockerfile
    container_name: laravel_app_new # Nouveau nom pour éviter le conflit
    restart: always
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8081:9000" # Laravel est maintenant sur 8081
    depends_on:
      - db

  # 2. LE FRONTEND (NEXT.JS / REACT)
  frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  # 3. LE SERVEUR WEB (NGINX) - Sur le port 80
  nginx:
    image: nginx:alpine
    container_name: nginx_server_new
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Ta config Nginx
    depends_on:
      - app
      - frontend

  # 4. LA BASE DE DONNÉES (POSTGRES)
  db:
    image: postgres:15
    container_name: postgres_db_new
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: