#!/usr/bin/env bash

# Script de démarrage rapide pour Windows/Mac/Linux
# Usage: bash start.sh (ou ./start.sh)

echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║          🕷️  KIPRIX SCRAPER ADMIN DASHBOARD              ║"
echo "║                    Startup Menu                            ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

echo "Choisissez le mode de démarrage:"
echo ""
echo "  1️⃣  Mode Développement (Manuel - 4 terminaux)"
echo "  2️⃣  Mode Docker (Tout en un)"
echo "  3️⃣  Mode Installation Rapide"
echo "  4️⃣  Voir Documentation"
echo ""
read -p "Entrez votre choix (1-4): " choice

case $choice in
  1)
    echo ""
    echo "📋 Mode Développement"
    echo ""
    echo "🔵 Ouvrez 4 terminaux et exécutez ces commandes:"
    echo ""
    echo "┌─ Terminal 1 (FastAPI - Backend Scraper)"
    echo "│"
    echo "│  $ cd akonou/projet"
    echo "│  $ python -m uvicorn fastapi_app:app --reload"
    echo "│"
    echo "│  ✅ http://localhost:8000"
    echo "│  🔍 Docs: http://localhost:8000/docs"
    echo "│"
    echo "├─ Terminal 2 (Laravel - API Admin)"
    echo "│"
    echo "│  $ cd akonou/back-laravel"
    echo "│  $ php artisan migrate"
    echo "│  $ php artisan serve"
    echo "│"
    echo "│  ✅ http://localhost:8000/api"
    echo "│"
    echo "├─ Terminal 3 (Laravel Scheduler - Cron)"
    echo "│"
    echo "│  $ cd akonou/back-laravel"
    echo "│  $ php artisan schedule:work"
    echo "│"
    echo "│  📅 Exécute les tâches planifiées"
    echo "│"
    echo "└─ Terminal 4 (Next.js - Dashboard)"
    echo ""
    echo "   $ cd akonou/front-next"
    echo "   $ npm run dev"
    echo ""
    echo "   ✅ http://localhost:3000/scraper"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    ;;
  
  2)
    echo ""
    echo "🐳 Mode Docker"
    echo ""
    echo "Exécutez:"
    echo ""
    echo "  $ cd akonou/infra"
    echo "  $ docker compose up --build"
    echo ""
    echo "Services:"
    echo "  ✅ Frontend (Next.js)  → http://localhost:3000"
    echo "  ✅ API (Laravel)       → http://localhost:8000/api"
    echo "  ✅ API (FastAPI Docs)  → http://localhost:8002/docs"
    echo "  ✅ PostgreSQL          → localhost:15432"
    echo ""
    echo "Arrêter:"
    echo "  $ docker compose down"
    echo ""
    ;;
  
  3)
    echo ""
    echo "⚡ Mode Installation Rapide"
    echo ""
    echo "Exécutez:"
    echo ""
    echo "  $ bash install.sh"
    echo ""
    echo "Cela va:"
    echo "  ✅ Vérifier les prérequis (Python, PHP, Node)"
    echo "  ✅ Installer toutes les dépendances"
    echo "  ✅ Générer les fichiers .env"
    echo "  ✅ Vous montrer comment démarrer"
    echo ""
    ;;
  
  4)
    echo ""
    echo "📖 Documentation"
    echo ""
    echo "Architecture Complète:"
    echo "  📄 akonou/projet/ARCHITECTURE.md"
    echo ""
    echo "Guide Démarrage Rapide:"
    echo "  📄 QUICKSTART.md"
    echo ""
    echo "Ouvrir les fichiers:"
    echo "  $ cat QUICKSTART.md"
    echo "  $ cat akonou/projet/ARCHITECTURE.md"
    echo ""
    ;;
  
  *)
    echo "Choix invalide. Veuillez exécuter à nouveau et choisir 1-4."
    exit 1
    ;;
esac

echo ""
echo "PREMIÈRE UTILISATION?"
echo ""
echo "1. Accédez au Dashboard: http://localhost:3000/scraper"
echo "2. Connectez-vous (register/login)"
echo "3. Allez à '+Ajouter une URL'"
echo "4. Remplissez les détails:"
echo ""
echo "   URL: https://www.kiprix.com/fr-gp"
echo "   Territoire: gp (Guadeloupe)"
echo "   Nom: Kiprix GP"
echo "   Max pages: 5"
echo "   Cron: 0 2 * * * (2h du matin)"
echo ""
echo "5. Cliquez '🚀 Lancer' pour tester"
echo "6. Vérifiez les logs en temps réel"
echo ""
echo "═════════════════════════════════════════════════════"
echo ""
