FROM php:8.2-cli

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    libpq-dev zip unzip \
    && docker-php-ext-install pdo pdo_pgsql

COPY . .

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]